export type MusicCredit = readonly [title: string, artist: string, license: string, source: string];

export const tracks: readonly MusicCredit[] = [
  ["Haru (Lo-Fi Version)", "Roa Music", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/roa-music-haru-lofi-version.html"],
  ["Slowly", "Tokyo Music Walker", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/tokyo-music-walker-slowly.html"],
  ["Your Little Wings", "Tokyo Music Walker", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/tokyo-music-walker-your-little-wings.html"],
  ["Calm And Sleeping Lo-Fi Hip Hop", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-calm-and-sleeping-lo-fi-hip-hop.html"],
  ["Hot Pepper", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-hot-pepper.html"],
  ["Bicycles", "Scandinavianz", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/scandinavianz-bicycles.html"],
  ["Luminance", "Ghostrifter Official", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/ghostrifter-official-luminance.html"],
  ["Sleepwalk Television", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-sleepwalk-television.html"],
  ["Downtown Walk", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-downtown-walk.html"],
  ["Rain, Book And Cup Of Tea", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-rain-book-and-cup-of-tea.html"],
  ["Dusk Horizon", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-dusk-horizon.html"],
  ["Forest", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-forest.html"],
  ["A Weekday In A Small Town", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-a-weekday-in-a-small-town.html"],
  ["Dandelion", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-dandelion.html"],
  ["Eternal Springtime", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-eternal-springtime.html"],
  ["Once Upon a Time", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-once-upon-a-time.html"],
  ["Over Oceans", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-over-oceans.html"],
  ["Galaxy", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-galaxy.html"],
  ["Bullies", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-bullies.html"],
  ["Make Me Happy", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-make-me-happy.html"],
  ["Antidepresseur", "Patchworker f.k.a. [friendzoned]", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/patchworker-fka-friendzoned-antidepresseur.html"],
  ["Shelter", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-shelter.html"],
  ["Uninvited", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-uninvited.html"],
  ["Equinox", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-equinox.html"],
  ["Birds of a Feather", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-birds-of-a-feather.html"],
  ["Wild Strawberry", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-wild-strawberry.html"],
  ["Green Tea", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-green-tea.html"],
  ["Flourish", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-flourish.html"],
  ["Lost Paradise", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-lost-paradise.html"],
  ["Frolic", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-frolic.html"],
  ["Gentle Breeze", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-gentle-breeze.html"],
  ["Field Of Fireflies", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-field-of-fireflies.html"],
  ["Wishing Well", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-wishing-well.html"],
  ["Please Hold Me", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-please-hold-me.html"],
  ["Star Bright", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-star-bright.html"],
  ["Bloom", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-bloom.html"],
  ["Dreams Come True", "Purrple Cat & Gerardo Mill\u00E1n", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-dreams-come-true.html"],
  ["Sand Castles", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-sand-castles.html"],
  ["Embrace", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-embrace.html"],
  ["Exhale", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-exhale.html"],
  ["Crescent Moon", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-crescent-moon.html"],
  ["Spring Showers", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-spring-showers.html"],
  ["Solitude", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-solitude.html"],
  ["Glowing Tides", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-glowing-tides.html"],
  ["Lost And Found", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-lost-and-found.html"],
  ["Day\u2019s End", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-days-end.html"],
  ["Calm Waters", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-calm-waters.html"],
  ["Secret Of The Forest", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-secret-of-the-forest.html"],
  ["Aether", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-aether.html"],
  ["Meteorites", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-meteorites.html"],
  ["Beautiful Day", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-beautiful-day.html"],
  ["Discovery", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-discovery.html"],
  ["Creation", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-creation.html"],
  ["Out Of The Blue", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-out-of-the-blue.html"],
  ["Dream Machine", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-dream-machine.html"],
  ["Come One, Come All", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-come-one-come-all.html"],
  ["Somewhere New", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-somewhere-new.html"],
  ["Phantom Waltz", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-phantom-waltz.html"],
  ["Moving Landscapes", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-moving-landscapes.html"],
  ["Take Me With You", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-take-me-with-you.html"],
  ["Sea Of Stars", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-sea-of-stars.html"],
  ["Forget-Me-Not", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-forget-me-not.html"],
  ["Wish You Were Here", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-wish-you-were-here.html"],
  ["Lullaby", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-lullaby.html"],
  ["Bird Bath", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-bird-bath.html"],
  ["Deja Vu", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-deja-vu.html"],
  ["Wishes", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-wishes.html"],
  ["Timeless", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-timeless.html"],
  ["Stars Collide", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-stars-collide.html"],
  ["Swingin\u2019", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-swingin.html"],
  ["Stasis", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-stasis.html"],
  ["A Place To Hide", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-a-place-to-hide.html"],
  ["Pitter Patter", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-pitter-patter.html"],
  ["Supernova", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-supernova.html"],
  ["Stranded", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-stranded.html"],
  ["Heart Of The Ocean", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-heart-of-the-ocean.html"],
  ["Ghost Town", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-ghost-town.html"],
  ["In The Past", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-in-the-past.html"],
  ["Sleeping Cat", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-sleeping-cat.html"],
  ["Silent Wood", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-silent-wood.html"],
  ["Time To Think", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-time-to-think.html"],
  ["Palm Tree", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-palm-tree.html"],
  ["Drifting", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-drifting.html"],
  ["Message In A Bottle", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-message-in-a-bottle.html"],
  ["Long Day", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-long-day.html"],
  ["Waiting For The Sun", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-waiting-for-the-sun.html"],
  ["Night Train", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-night-train.html"],
  ["Sky Lake", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-sky-lake.html"],
  ["Underwater Cavern", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-underwater-cavern.html"],
  ["Low Tide", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-low-tide.html"],
  ["Seashells", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-seashells.html"],
  ["Pillow Fort", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-pillow-fort.html"],
  ["Visions", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-visions.html"],
  ["Dark Forest", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-dark-forest.html"],
  ["Happy Trails", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-happy-trails.html"],
  ["Rocky Shores", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-rocky-shores.html"],
  ["Through The Trees", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-through-the-trees.html"],
  ["Birdhouse", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-birdhouse.html"],
  ["Echoes Of Yesterday", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-echoes-of-yesterday.html"],
  ["Magical Moments", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-magical-moments.html"],
  ["Once In A Lifetime", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-once-in-a-lifetime.html"],
  ["Pineapple Popsicle", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-pineapple-popsicle.html"],
  ["Changes", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-changes.html"],
  ["Rooftop Rendezvous", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-rooftop-rendezvous.html"],
  ["Passing Time", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-passing-time.html"],
  ["Exploration", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-exploration.html"],
  ["Crossroads", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-crossroads.html"],
  ["Desert Rain", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-desert-rain.html"],
  ["After Hours", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-after-hours.html"],
  ["Chugging Along", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-chugging-along.html"],
  ["Morning Dew", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-morning-dew.html"],
  ["Tunnels", "Purrple Cat", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/purrple-cat-tunnels.html"],
  ["Sandstorm", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-sandstorm.html"],
  ["Exist", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-exist.html"],
  ["EVENING NIGHTS", "Mehul ShaRma", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/mehul-sharma-evening-nights.html"],
  ["XII", "Nihility Stuffs", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://soundcloud.com/nihilitystuffs-lab/xii-lofi-type-beat-free"],
  ["Entwined - 4AM", "Mr Hexadus", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.soundclick.com/track/15066946/mr-hexadus/entwined-4am"],
  ["Distant Memories", "Catalin Chirila", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://opentunes.io/music/distant-memories"],
  ["Sunlit Saturdays", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-sunlit-saturdays.html"],
  ["Breakfast in Paris", "Alex-Productions", "Creative Commons / Attribution 3.0 Unported License (CC BY 3.0)", "https://www.free-stock-music.com/alex-productions-breakfast-in-paris.html"],
  ["Hometown Rain", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-hometown-rain.html"],
  ["Wonderland", "Purrple Cat", "Creative Commons / Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)", "https://www.free-stock-music.com/purrple-cat-wonderland.html"],
  ["Komorebi", "FSM Team & < e s c p >", "Creative Commons / Attribution 4.0 International (CC BY 4.0)", "https://www.free-stock-music.com/fsm-team-escp-komorebi.html"],
] as const;
